#!/bin/sh

SWAPS=`swapon -s | grep file | wc -l`

if [ $SWAPS -gt 0 ]
then
	NODE_PATH=/usr/lib/node_modules /usr/bin/nodejs $@
else
	NODE_PATH=/usr/lib/node_modules /usr/bin/nodejs --stack_size=1024 --max_old_space_size=20 --max_new_space_size=2048 --max_executable_size=5 --gc_global --gc_interval=100 $@
fi

